export { ReactComponent as ArrowLeftIcon } from './arrowLeft.svg'
export { ReactComponent as ArrowRightIcon } from './arrowRight.svg'
export { ReactComponent as BoardIcon } from './board.svg'
export { ReactComponent as ClassIcon } from './class.svg'
export { ReactComponent as GraduationIcon } from './graduation.svg'
export { ReactComponent as LogoIcon } from './logo.svg'
export { ReactComponent as StudentIcon } from './student.svg'
export { ReactComponent as LoginIcon } from './subtract.svg'
